### ISSUE TITLE
Error: Missing required @Command

### ISSUE THREAD

**Issue by Lemar98** [bundabrg/bcf#20]
I have plugin A and plugin B.

In plugin A, I registered the main command without any subcommands.

In plugin B, I created a subcommand class and inherited my main command class from my plugin A, then I registered it the same way.

When I run these 2 plugins, my plugin B tells me that I don't have @Command annotation in my subcommand class, but judging by the documentation, I just need to inherit from the main command and leave only the @Arg annotation in the subcommand class.

Why doesn't this work for me?

plugin A: https://pastebin.com/YyJBXKqY
plugin B: https://pastebin.com/2ee7yyQr
error: https://pastebin.com/ExeTy1GN

**Comment by bundabrg** [comment]
I've changed things a little (so you may need to recheck the docs) to support passing an object to register instead of class name. Check https://bundabrg.github.io/bcf/api/#bukkitbungeecord.

Instead of inheriting from the parent class you register it as a subcommand with the manager and pass the parent class as a parameter. Its a little different than previous where you just inherited from the parent class which IMHO was neater but meant it was impossible to pass an instantiated class.

**Comment by Lemar98** [comment]
Thanks, it's work for me!
